# Generated by Django 4.2.7 on 2026-04-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_role_teamtask_subworkerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Admin', 'Awaiting Admin Configuration'), ('Loan Approved', 'Loan Approved by Admin'), ('Loan Rejected', 'Loan Rejected'), ('Direct Pay Confirmed', 'Direct Pay Confirmed'), ('Completed', 'Installation Completed')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkerUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='worker_updates/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.teamtask')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bill', models.FileField(blank=True, null=True, upload_to='booking_docs/bills/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='booking_docs/aadhar/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='booking_docs/pan/')),
                ('bank_details', models.FileField(blank=True, null=True, upload_to='booking_docs/bank/')),
                ('house_tax', models.FileField(blank=True, null=True, upload_to='booking_docs/tax/')),
                ('bank_statement_6m', models.FileField(blank=True, null=True, upload_to='booking_docs/statements/')),
                ('panel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('wire_type', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('inverter_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rod_type', models.CharField(blank=True, max_length=50, null=True)),
                ('rod_count', models.IntegerField(default=0)),
                ('panel_count', models.IntegerField(default=0)),
                ('final_invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.booking')),
            ],
        ),
    ]
