# Generated by Django 4.2.7 on 2026-04-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_booking_status_workerupdate_bookingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted by Agent'), ('Awaiting Admin', 'Awaiting Admin Configuration'), ('Loan Approved', 'Loan Approved by Admin'), ('Loan Rejected', 'Loan Rejected'), ('Direct Pay Confirmed', 'Direct Pay Confirmed'), ('Completed', 'Installation Completed')], default='Pending', max_length=50),
        ),
    ]
