# Generated by Django 6.0.3 on 2026-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted by Agent'), ('Awaiting Admin', 'Awaiting Admin Configuration'), ('Loan Approved', 'Loan Approved by Admin'), ('Loan Rejected', 'Loan Rejected'), ('Direct Pay Confirmed', 'Direct Pay Confirmed'), ('Dispatched', 'Dispatched to Worker'), ('Completed', 'Installation Completed')], default='Pending', max_length=50),
        ),
    ]
