# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
