# Generated by Django 4.2.7 on 2026-04-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_confirmed_time_to_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
