# Generated by Django 4.2.7 on 2026-04-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='Pending Assignment', max_length=20, null=True)),
                ('address', models.TextField(blank=True, default='HQ Base Deployment', null=True)),
                ('status', models.CharField(default='ON DUTY', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='agent_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
