# Generated by Django 4.2.7 on 2026-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkerprofile',
            name='raw_password',
            field=models.CharField(blank=True, default='pass123!', max_length=100, null=True),
        ),
    ]
