# Generated by Django 4.2.7 on 2026-04-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subworkerprofile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkerprofile',
            name='address',
            field=models.TextField(blank=True, default='No Address Linked', null=True),
        ),
        migrations.AddField(
            model_name='subworkerprofile',
            name='experience',
            field=models.CharField(blank=True, default='Junior', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subworkerprofile',
            name='phone',
            field=models.CharField(blank=True, default='Not Provided', max_length=20, null=True),
        ),
    ]
