# Generated by Django 4.2.7 on 2026-04-20 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_subworkerprofile_address_subworkerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='sub_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sub_worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_installations', to=settings.AUTH_USER_MODEL),
        ),
    ]
