# Generated by Django 4.2.7 on 2026-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='materials_used',
            field=models.TextField(blank=True, help_text='Materials used during intervention', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_photo',
            field=models.FileField(blank=True, null=True, upload_to='support_resolutions/'),
        ),
    ]
