# Generated by Django 4.2.7 on 2026-04-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_supportticket_materials_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('panel', 'Solar Panel'), ('wire', 'Wire'), ('battery', 'Battery'), ('rod', 'Mounting Rod'), ('inverter', 'Inverter'), ('other', 'Other Materials')], max_length=20)),
                ('specification', models.TextField(blank=True, help_text='e.g. 550W, 4sq mm, 150Ah', null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hardware_inventory/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
